# Generated by Django 5.2.8 on 2025-11-21 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_category_options_contact_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='decription',
            new_name='description',
        ),
    ]
